import heapq
import json

import jsonpath
import jsonpath as jsonpath

a = {
    "success": "true",
    "status": "success",
    "redirect": "null",
    "msg": "查询成功！",
    "data": {
        "storeLocation": [
            {
                "id": "295",
                "number": "117601",
                "name": "默认门店",
                "status": "0",
                "isDefault": "1",
                "defaultKZ": "快准仓",
                "defaultPDM": "第三方仓",
                "locationList": [
                    {
                        "id": "640",
                        "name": "快准仓",
                        "number": "KZ001",
                        "type": "0",
                        "defaultLocation": "1",
                        "disable": "0"
                    },
                    {
                        "id": "641",
                        "name": "第三方仓",
                        "number": "S001",
                        "type": "1",
                        "defaultLocation": "1",
                        "disable": "0"
                    },
                    {
                        "id": "11606",
                        "name": "E站01",
                        "number": "CKZ002",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11607",
                        "name": "E站02",
                        "number": "CKZ003",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11608",
                        "name": "E站03",
                        "number": "CKZ004",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11611",
                        "name": "快准仓_2",
                        "number": "CKZ005",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11612",
                        "name": "0602-测试移动库-高先生",
                        "number": "CKZ006",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11613",
                        "name": "0604移动仓",
                        "number": "CKZ007",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11622",
                        "name": "第三方仓库2",
                        "number": "S011",
                        "type": "1",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11631",
                        "name": "测试快准仓",
                        "number": "CKZ012",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11638",
                        "name": "移动仓测试0729",
                        "number": "CKZ013",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11639",
                        "name": "移动仓测试0730",
                        "number": "CKZ014",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11640",
                        "name": "测试移动仓",
                        "number": "CKZ015",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11641",
                        "name": "移动仓库0731",
                        "number": "CKZ016",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11696",
                        "name": "测试仓库",
                        "number": "CKZ017",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11697",
                        "name": "微仓秋月",
                        "number": "CKZ018",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11698",
                        "name": "微仓测试qy",
                        "number": "CKZ019",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11700",
                        "name": "test-111",
                        "number": "CKZ020",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11701",
                        "name": "order调试-峰哥维修厂",
                        "number": "CKZ021",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11702",
                        "name": "y测试仓1-铺货仓1",
                        "number": "CKZ022",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11704",
                        "name": "y测试仓2-非铺货仓2",
                        "number": "CKZ023",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11705",
                        "name": "我日昍晶",
                        "number": "CKZ024",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11706",
                        "name": "七院仓",
                        "number": "CKZ025",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11707",
                        "name": "ycd3微仓-非铺货",
                        "number": "CKZ026",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11711",
                        "name": "ycd4微仓",
                        "number": "CKZ027",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11712",
                        "name": "123456",
                        "number": "CKZ028",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11714",
                        "name": "微仓0210",
                        "number": "CKZ029",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11716",
                        "name": "云修仓",
                        "number": "CKZ030",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11719",
                        "name": "旺财一号",
                        "number": "CKZ031",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11721",
                        "name": "大奔仓",
                        "number": "CKZ032",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11722",
                        "name": "三生三世",
                        "number": "CKZ033",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11723",
                        "name": "测试老用户",
                        "number": "CKZ034",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11726",
                        "name": "222",
                        "number": "CKZ035",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11727",
                        "name": "微仓101",
                        "number": "CKZ036",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11728",
                        "name": "微仓202",
                        "number": "CKZ037",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11729",
                        "name": "微仓103",
                        "number": "CKZ038",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11755",
                        "name": "微仓测试",
                        "number": "CKZ039",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11759",
                        "name": "快准微仓测试",
                        "number": "CKZ040",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11760",
                        "name": "修理厂a",
                        "number": "CKZ041",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11761",
                        "name": "十三点",
                        "number": "CKZ042",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11762",
                        "name": "小拇指",
                        "number": "CKZ043",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11763",
                        "name": "微仓对账",
                        "number": "CKZ044",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11766",
                        "name": "洪合正道",
                        "number": "CKZ047",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11769",
                        "name": "19900000014",
                        "number": "CKZ048",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11773",
                        "name": "0013",
                        "number": "CKZ049",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11795",
                        "name": "创建",
                        "number": "CKZ050",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11818",
                        "name": "xss",
                        "number": "CKZ051",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11819",
                        "name": "测试站内信的微仓",
                        "number": "CKZ052",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    },
                    {
                        "id": "11820",
                        "name": "test",
                        "number": "CKZ053",
                        "type": "0",
                        "defaultLocation": "0",
                        "disable": "0"
                    }
                ]
            }
        ],
        "rows": [
            {
                "address": "浙江省_嘉兴市_南湖区_中环南路999号汽车商贸园天德嘉兴汽配城7幢7-2",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 640,
                "locationNo": "KZ001",
                "name": "快准仓",
                "phone": "18806529812",
                "type": 0,
                "isPurchase": 1,
                "is_move": "0",
                "move_type": 1,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "1"
            },
            {
                "address": "0",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 641,
                "locationNo": "S001",
                "name": "第三方仓",
                "phone": "null",
                "type": 1,
                "isPurchase": 0,
                "is_move": "0",
                "move_type": 1,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "1"
            },
            {
                "address": "浙江省_杭州市_下城区_东新路184号华驰汽修市场4区12-14号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11606,
                "locationNo": "CKZ002",
                "name": "E站01",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_文一西路969号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11607,
                "locationNo": "CKZ003",
                "name": "E站02",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_下城区_朝晖路211号中山花园裙楼",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11608,
                "locationNo": "CKZ004",
                "name": "E站03",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11611,
                "locationNo": "CKZ005",
                "name": "快准仓_2",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "0",
                "move_type": 1,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_西湖区_龙井路1号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11612,
                "locationNo": "CKZ006",
                "name": "0602-测试移动库-高先生",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "0",
                "move_type": 1,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_西湖区_翠苑街道万塘路252号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11613,
                "locationNo": "CKZ007",
                "name": "0604移动仓",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_嘉兴市_南湖区_中环南路999号汽车商贸园天德嘉兴汽配城7幢7-2",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11614,
                "locationNo": "KZ002",
                "name": "快准仓_1432",
                "phone": "18806529812",
                "type": 0,
                "isPurchase": 1,
                "is_move": "0",
                "move_type": 1,
                "storeId": "",
                "storeName": "",
                "storeNumber": "",
                "isDefault": "0"
            },
            {
                "address": "测试3",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11618,
                "locationNo": "KZ003",
                "name": "快准仓_9309",
                "phone": "18806529812",
                "type": 0,
                "isPurchase": 1,
                "is_move": "0",
                "move_type": 1,
                "storeId": "",
                "storeName": "",
                "storeNumber": "",
                "isDefault": "0"
            },
            {
                "address": "",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11619,
                "locationNo": "CKZ010",
                "name": "测试AAA",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "0",
                "move_type": 1,
                "storeId": "",
                "storeName": "",
                "storeNumber": "",
                "isDefault": "0"
            },
            {
                "address": "",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11622,
                "locationNo": "S011",
                "name": "第三方仓库2",
                "phone": "null",
                "type": 1,
                "isPurchase": 0,
                "is_move": "0",
                "move_type": 1,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11631,
                "locationNo": "CKZ012",
                "name": "测试快准仓",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "0",
                "move_type": 1,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_联胜路13号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11638,
                "locationNo": "CKZ013",
                "name": "移动仓测试0729",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_文一西路1286附近",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11639,
                "locationNo": "CKZ014",
                "name": "移动仓测试0730",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_上城区_上城区",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11640,
                "locationNo": "CKZ015",
                "name": "测试移动仓",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_文一西路1286附近",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11641,
                "locationNo": "CKZ016",
                "name": "移动仓库0731",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_溪望路",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11696,
                "locationNo": "CKZ017",
                "name": "测试仓库",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_滨江区_网商路899号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11697,
                "locationNo": "CKZ018",
                "name": "微仓秋月",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_文一西路969号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11698,
                "locationNo": "CKZ019",
                "name": "微仓测试qy",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "河南省_南阳市_南召县_顺达水电安装",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11700,
                "locationNo": "CKZ020",
                "name": "test-111",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_滨江区_六和路368号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11701,
                "locationNo": "CKZ021",
                "name": "order调试-峰哥维修厂",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_5号线",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11702,
                "locationNo": "CKZ022",
                "name": "y测试仓1-铺货仓1",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_萧山区_瓜沥镇靖一村",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11704,
                "locationNo": "CKZ023",
                "name": "y测试仓2-非铺货仓2",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_西湖区_天目山路305号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11705,
                "locationNo": "CKZ024",
                "name": "我日昍晶",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_拱墅区_莫干山路766号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11706,
                "locationNo": "CKZ025",
                "name": "七院仓",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_仓前街道绿汀路3号(原仓前大酒店北侧)",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11707,
                "locationNo": "CKZ026",
                "name": "ycd3微仓-非铺货",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_(在建)机场轨道快线;5号线",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11711,
                "locationNo": "CKZ027",
                "name": "ycd4微仓",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_1300M路社区接驳巴士;148路;220路公交快线;2401M路;2401",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11712,
                "locationNo": "CKZ028",
                "name": "123456",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_西湖区_龙井路1号西湖风景名胜区内",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11714,
                "locationNo": "CKZ029",
                "name": "微仓0210",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_上城区_白马庄街云亭公寓",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11716,
                "locationNo": "CKZ030",
                "name": "云修仓",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_滨江区_网商路699号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11719,
                "locationNo": "CKZ031",
                "name": "旺财一号",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_闲富中路171号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11721,
                "locationNo": "CKZ032",
                "name": "大奔仓",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_余杭街道学君里(小区)商铺24号运溪路24号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11722,
                "locationNo": "CKZ033",
                "name": "三生三世",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_钱塘区_经四路与纬八路交叉路口往西约260米",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11723,
                "locationNo": "CKZ034",
                "name": "测试老用户",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_上城区_天城路1号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11726,
                "locationNo": "CKZ035",
                "name": "222",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_文一西路1286附近",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11727,
                "locationNo": "CKZ036",
                "name": "微仓101",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_钱塘区_杭州下沙新加坡科技园4号楼三楼",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11728,
                "locationNo": "CKZ037",
                "name": "微仓202",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_余杭区_文一西路1286附近",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11729,
                "locationNo": "CKZ038",
                "name": "微仓103",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_台州市_椒江区_纬二路158-5号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11755,
                "locationNo": "CKZ039",
                "name": "微仓测试",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_上城区_解放东路29号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11759,
                "locationNo": "CKZ040",
                "name": "快准微仓测试",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_上城区_解放东路29号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11760,
                "locationNo": "CKZ041",
                "name": "修理厂a",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_上城区_富春路701号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11761,
                "locationNo": "CKZ042",
                "name": "十三点",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_建德市_建德4路(雅鼎路线)",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11762,
                "locationNo": "CKZ043",
                "name": "小拇指",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_上城区_城星路59号东杭大厦一楼乡村基停车场出口",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11763,
                "locationNo": "CKZ044",
                "name": "微仓对账",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11764,
                "locationNo": "CKZ045",
                "name": "1176-01仓",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "0",
                "move_type": 1,
                "storeId": "",
                "storeName": "",
                "storeNumber": "",
                "isDefault": "0"
            },
            {
                "address": "",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11765,
                "locationNo": "CKZ046",
                "name": "gbf-仓库",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "0",
                "move_type": 1,
                "storeId": "",
                "storeName": "",
                "storeNumber": "",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_萧山区_北干街道博学路610号萧山区科技创新中心C楼一层商业区07室商铺",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11766,
                "locationNo": "CKZ047",
                "name": "洪合正道",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_上城区_高德置地广场5楼L510室",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11769,
                "locationNo": "CKZ048",
                "name": "19900000014",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_拱墅区_萍水街299号萍水太合商业中心6幢104室",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11773,
                "locationNo": "CKZ049",
                "name": "0013",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_滨江区_六和路368号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11795,
                "locationNo": "CKZ050",
                "name": "创建",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_萧山区_曹公堂45号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11818,
                "locationNo": "CKZ051",
                "name": "xss",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_拱墅区_香积寺东路93号(东新园地铁站A口步行310米)",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11819,
                "locationNo": "CKZ052",
                "name": "测试站内信的微仓",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 2,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            },
            {
                "address": "浙江省_杭州市_上城区_全福桥路2号",
                "delete": "false",
                "allowNeg": "false",
                "deptId": 0,
                "empId": 0,
                "groupx": "null",
                "id": 11820,
                "locationNo": "CKZ053",
                "name": "test",
                "phone": "null",
                "type": 0,
                "isPurchase": 0,
                "is_move": "1",
                "move_type": 3,
                "storeId": "295",
                "storeName": "默认门店",
                "storeNumber": "117601",
                "isDefault": "0"
            }
        ],
        "total": 1,
        "records": "54",
        "page": 1
    }
}

b = {
    "data":{
        "page":1,
        "records":"68",
        "total":4,
        "rows":[
            {
                "id":"41139746",
                "iid":"101087903",
                "invId":"7029",
                "locationId":"638",
                "saCode":"PO1175221011135151901",
                "invName":"JO00413 1601000537 机油滤芯 Φ65.5*M20×1.5*76",
                "categoryId":"110038995",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":1,
                "minNum":"1",
                "inQty":1,
                "locationName":"啊仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139745",
                "iid":"101087903",
                "invId":"6990",
                "locationId":"638",
                "saCode":"PO1175221011135151901",
                "invName":"JO00812 1601000498 机油滤芯 Φ65.5*3/4",
                "categoryId":"110038995",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":1,
                "minNum":"1",
                "inQty":1,
                "locationName":"啊仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139576",
                "iid":"101087827",
                "invId":"10485",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"防冻液/绿色/-25° 2kg 1301000031 防冻液 2kg",
                "categoryId":"110039092",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":1,
                "minNum":"12",
                "inQty":12,
                "locationName":"啊仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139575",
                "iid":"101087827",
                "invId":"10484",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"巨江防冻液/红色/-25° 2kg 巨江 1301000030 防冻液 2kg",
                "categoryId":"110039092",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":0.01,
                "minNum":"12",
                "inQty":12,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139574",
                "iid":"101087827",
                "invId":"10483",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"巨江防冻液/绿色/-15° 2kg 巨江 1301000029 防冻液 2kg",
                "categoryId":"110039092",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":0.01,
                "minNum":"12",
                "inQty":12,
                "locationName":"快准仓",
                "lockNum":1,
                "cashDisRate":1
            },
            {
                "id":"41139573",
                "iid":"101087827",
                "invId":"10482",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"巨江防冻液/红色/-15° 2kg 巨江 1301000028 防冻液 2kg",
                "categoryId":"110039092",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":0.01,
                "minNum":"12",
                "inQty":12,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139572",
                "iid":"101087827",
                "invId":"10471",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"H7 12V55W 鹰牌 1901020126 鹰牌灯泡",
                "categoryId":"110039043",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":1,
                "minNum":"10",
                "inQty":10,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139571",
                "iid":"101087827",
                "invId":"10321",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"V8 SN 5W-30/4L 鹰旗 1102000053 汽机油 4L",
                "categoryId":"110038979",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":2,
                "minNum":"3",
                "inQty":3,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139570",
                "iid":"101087827",
                "invId":"10320",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"V8 SN 5W-30/1L 鹰旗 1102000052 汽机油 1L",
                "categoryId":"110038979",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":10,
                "minNum":"12",
                "inQty":12,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139569",
                "iid":"101087827",
                "invId":"10318",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"V8 SN 5W-40/1L 鹰旗 1102000050 汽机油 1L",
                "categoryId":"110038979",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":0.01,
                "minNum":"12",
                "inQty":12,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139568",
                "iid":"101087827",
                "invId":"10234",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"JC05612H 巨江 1503030008 空调滤清器 193*214*29",
                "categoryId":"110038999",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":2,
                "minNum":"1",
                "inQty":1,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139566",
                "iid":"101087827",
                "invId":"7048",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"JO00256 巨江 1601000556 机油滤芯 Φ68*3/4'-16UNF*67",
                "categoryId":"110038995",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":1,
                "minNum":"1",
                "inQty":1,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139565",
                "iid":"101087827",
                "invId":"7043",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"JO00211 巨江 1601000551 机油滤芯 Φ68*M20×1.5*87",
                "categoryId":"110038979",
                "noNeedFj":"false",
                "status":"2",
                "isGift":"否",
                "price":1,
                "minNum":"1",
                "inQty":1,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139563",
                "iid":"101087827",
                "invId":"7003",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"JO05841 巨江 1601000511 机油滤芯 Φ76*3/4'-16UNF*79",
                "categoryId":"110038995",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":66.66,
                "minNum":"1",
                "inQty":1,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41139562",
                "iid":"101087827",
                "invId":"6990",
                "locationId":"638",
                "saCode":"PO1175221009105817231",
                "invName":"JO00812 巨江 1601000498 机油滤芯 Φ65.5*3/4",
                "categoryId":"110038995",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":1,
                "minNum":"1",
                "inQty":1,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41138473",
                "iid":"101087166",
                "invId":"1086",
                "locationId":"638",
                "saCode":"PO1175220823111316601",
                "invName":"6PK1075 盖茨 1701020386 多楔带 8552-5108",
                "categoryId":"110038979",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":2,
                "minNum":"1",
                "inQty":2,
                "locationName":"快准仓",
                "lockNum":1,
                "cashDisRate":1
            },
            {
                "id":"41137802",
                "iid":"101086756",
                "invId":"10491",
                "locationId":"638",
                "saCode":"PO1175220718110058121",
                "invName":"巨江防冻液/绿色/-45° 4kg 巨江 1301000037 防冻液 4kg",
                "categoryId":"110039092",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":1,
                "minNum":"6",
                "inQty":20,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            },
            {
                "id":"41137801",
                "iid":"101086755",
                "invId":"10490",
                "locationId":"638",
                "saCode":"PO1175220718110058121",
                "invName":"巨江防冻液/红色/-45° 4kg 巨江 1301000036 防冻液 4kg",
                "categoryId":"110039092",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":2,
                "minNum":"6",
                "inQty":20,
                "locationName":"快准仓",
                "lockNum":1,
                "cashDisRate":1
            },
            {
                "id":"41137800",
                "iid":"101086755",
                "invId":"10489",
                "locationId":"638",
                "saCode":"PO1175220718110058121",
                "invName":"巨江防冻液/绿色/-35° 4kg 巨江 1301000035 防冻液 4kg",
                "categoryId":"110039092",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":1,
                "minNum":"6",
                "inQty":20,
                "locationName":"快准仓",
                "lockNum":1,
                "cashDisRate":1
            },
            {
                "id":"41137799",
                "iid":"101086755",
                "invId":"10488",
                "locationId":"638",
                "saCode":"PO1175220718110058121",
                "invName":"巨江防冻液/红色/-35° 4kg 巨江 1301000034 防冻液 4kg",
                "categoryId":"110039092",
                "noNeedFj":"false",
                "status":"1",
                "isGift":"否",
                "price":2,
                "minNum":"6",
                "inQty":40,
                "locationName":"快准仓",
                "lockNum":0,
                "cashDisRate":1
            }
        ]
    }
}

c = jsonpath.jsonpath(a, '$...locationList[?(@.number=="KZ001")].id')
get_goods_info = []
for i in b["data"]["rows"]:
    # print(i)
    if i["status"] == "1" and i["locationId"] == "638" and i["inQty"] > i["lockNum"] and i["isGift"] == "否":
        get_goods_info.append(i)
print(json.dumps(get_goods_info))
d = heapq.nlargest(1, get_goods_info, key=lambda s: s["inQty"] - s["lockNum"])
# test_iter = iter(get_goods_info)
# for i in get_goods_info:
#     print(i["iid"])


print(json.dumps(d))
# e = heapq.nlargest(2, get_goods_info, key=lambda s: s["iid"] == s["iid"] and s["inQty"] - s["lockNum"])
